---
#title: "Дружеские посиделки. Сайт про Дзадзэн"
baseURL: "https://friendly-sitting.ru/"
theme: "zen"
defaultContentLanguage: "ru"
metaDataFormat: "yaml"

#params:
#  copyrighttitle: "friendly-sitting.ru"

languages:
  ru:
    weight: 1
    title: "Сайт про Дзадзэн"
    languageCode: "ru-ru"
    footer: "Сайт сгенерирован [Hugo](https://gohugo.io/) и [Zen theme](https://github.com/frjo/hugo-theme-zen)."
    params:
      copyrighttitle: "friendly-sitting.ru"
      LanguageName: "Русский"
      dateformat: "2 January, 2006"
  en:
    weight: 2
    title: "Wedsite about ZaZen"
    languageCode: "en-en"
    footer: "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
    params:
      copyrighttitle: "friendly-sitting.ru"
      LanguageName: "English"
      dateformat: "2 January, 2006"

pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
#author:
#  name: "Your Name"
#  url: "https://example.org/somepage"
#  avatar: "path/to/some-image.jpg"

outputs:
  home: ["HTML","RSS", "JSON"]
  section: ["HTML","RSS", "JSON"]

#permalinks:
#post = "/:year/:month/:urltitle/"
#post: "/blog/:year/:slug/"

params:
  cacheBustCSS: false
  cacheBustJS: false
  contact: "friendly.sitting.ru@gmail.com"
  #copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  description: "The zen theme for Hugo example site."

#  favicon: "icon-64.png"
  feedlinks: false           # Show feed links in the footer.

#  icon: "apple-touch-icon-180.png"
#  image: "xdeb-org.jpg"
  enableGitInfo: false
  imageMaxWidth: 400
  jquery: false
  languageDir: "ltr"
  logo: false
  mobileMenu: false
  poweredby: false
  search: false
  searchSize: 20
  sidebar: true
  submitted: true             # Show author and date information for a post.
